## contact alignment ##
## 2025-09-16 16:06 ##

seq_1ITB <- "MKVLLRLICFIALLISSLEADKCKEREEKIILVSSANEIDVRPCPLNPNE------------HKGTITWYKDDSKTPVSTEQASRIHQHKEKLWFVPAKVEDSGHYYCVVRNSSYCLRIKISAKFVENEPNLCYNAQAIFKQKLPVAGDGGLVCPYMEFFKNENNELPKLQWYKDCKPLLLDNIHFSGVK--DRLIVMNVAEKHRGNYTCHASYTYLGKQYPITRVIEFITLEENKPTRPVIVSPANETMEVDLGSQIQLICNVTG----QLSDIAYWKWNGSVIDEDDPVLGEDYYSVENPANKRRSTLITVLNISEIESRFYKHPFTCFAKNTHGIDAAYIQLIYPVTNFQKHMIGICVTLTVIIVCSVFIYKIFKIDIVLWYRDSCYDFLPIKASDGKTYDAYILYPKTVGEGSTSDCDIFVFKVLPEVLEKQCGYKLFIYGRDDYVGEDIVEVINENVKKSRRLIIILVRETSGFSWLGGSSEEQIAMYNALVQDGIKVVLLELEKIQDYEKMPESIKFIKQKHGAIRWSGDFTQGPQSAKTRFWKNVRYHMPVQRRSPSSKHQLLSPATKEKLQREAHVPLG"

seq_3O4O <- "MLRLYVLVMGVSAFTLQPAAHTGAARSCRFRGRHYKREFRLEGEPVALRCPQVPYWLWASVSPRINLTWHKNDSARTVPGEEETRMWAQDGALWLLPALQEDSGTYVCTTRNASYCDKMSIELRVFEN--TDAFLPFISYPQILTLSTSGVLVCPDLSEFTR-DKTDVKIQWYKDSLLLDKDNEKFLSVRGTTHLLVHDVALEDAGYYRCVLTFAHEGQQYNITRSIELRIKKKKEETIPVIISPL-KTISASLGSRLTIPCKVFLGTGTPLTTMLWWTANDTHIESAYPGG-----------------------------RVTEGPRQEYSENNE-NYIEVPLIFDPVTREDLHMDFKCVVHNTLSFQTLRTTVKEASSTFSWG------------------------------------------------------------------------------------IVLAPLSLAFLVLGGIWMHRRCKHRTGKADGLTVLWPHHQDFQSYPK-----------------------------------------------------------------------"

# split sequences

seq_1ITB_split <- unlist(strsplit(seq_1ITB, split = ""))
seq_3O4O_split <- unlist(strsplit(seq_3O4O, split = ""))

# replace gaps with NA

seq_1ITB_split[seq_1ITB_split=="-"] <- NA
seq_3O4O_split[seq_3O4O_split=="-"] <- NA

# residue numbers

counter_1ITB <- 1
counter_3O4O <- 1
index_list_1ITB <- rep(-1, length(seq_1ITB_split))
index_list_3O4O <- rep(-1, length(seq_3O4O_split))

for (i in 1:length(seq_1ITB_split)) {
  if (!is.na(seq_1ITB_split[i])) {
    index_list_1ITB[i] <- counter_1ITB
    counter_1ITB <- counter_1ITB+1
  }
}

for (i in 1:length(seq_3O4O_split)) {
  if (!is.na(seq_3O4O_split[i])) {
    index_list_3O4O[i] <- counter_3O4O
    counter_3O4O <- counter_3O4O+1
  }
}

# create dataframe

contacts_df <- data.frame(
  receptor_1 = seq_1ITB_split,
  receptor_2 = seq_3O4O_split,
  receptor1_index = index_list_1ITB,
  receptor2_index = index_list_3O4O,
  stringsAsFactors = FALSE
)

write.csv(contacts_df, "~/Dropbox/getcontacts/receptors_il1b/contact_alignment.csv")
