## contact alignment ##
## 2025-09-16 16:06 ##

seq_1ITB <- "MKVLLRLICFIALLISSLEADKCKEREEKIILVSSANEIDVRPCPLNPNE------------HKGTITWYKDDSKTPVSTEQASRIHQHKEKLWFVPAKVEDSGHYYCVVRNSSYCLRIKISAKFVENEPNLCYNAQAIFKQKLPVAGDGGLVCPYMEFFKNENNELPKLQWYKDCKPLLLDNIHFSGVK--DRLIVMNVAEKHRGNYTCHASYTYLGKQYPITRVIEFITLEENKPTRPVIVSPANETMEVDLGSQIQLICNVTG----QLSDIAYWKWNGSVIDEDDPVLGEDYYSVENPANKRRSTLITVLNISEIESRFYKHPFTCFAKNTHGIDAAYIQLIYPVTNFQKHMIGICVTLTVIIVCSVFIYKIFKIDIVLWYRDSCYDFLPIKASDGKTYDAYILYPKTVGEGSTSDCDIFVFKVLPEVLEKQCGYKLFIYGRDDYVGEDIVEVINENVKKSRRLIIILVRETSGFSWLGGSSEEQIAMYNALVQDGIKVVLLELEKIQDYEKMPESIKFIKQKHGAIRWSGDFTQGPQSAKTRFWKNVRYHMPVQRRSPSSKHQLLSPATKEKLQREAHVPLG"

seq_3O4O <- "MLRLYVLVMGVSAFTLQPAAHTGAARSCRFRGRHYKREFRLEGEPVALRCPQVPYWLWASVSPRINLTWHKNDSARTVPGEEETRMWAQDGALWLLPALQEDSGTYVCTTRNASYCDKMSIELRVFEN--TDAFLPFISYPQILTLSTSGVLVCPDLSEFTR-DKTDVKIQWYKDSLLLDKDNEKFLSVRGTTHLLVHDVALEDAGYYRCVLTFAHEGQQYNITRSIELRIKKKKEETIPVIISPL-KTISASLGSRLTIPCKVFLGTGTPLTTMLWWTANDTHIESAYPGG-----------------------------RVTEGPRQEYSENNE-NYIEVPLIFDPVTREDLHMDFKCVVHNTLSFQTLRTTVKEASSTFSWG------------------------------------------------------------------------------------IVLAPLSLAFLVLGGIWMHRRCKHRTGKADGLTVLWPHHQDFQSYPK-----------------------------------------------------------------------"

# split sequences

seq_1ITB_split <- unlist(strsplit(seq_1ITB, split = ""))
seq_3O4O_split <- unlist(strsplit(seq_3O4O, split = ""))

# replace gaps with NA

seq_1ITB_split[seq_1ITB_split=="-"] <- NA
seq_3O4O_split[seq_3O4O_split=="-"] <- NA

# create dataframe

contacts_df <- data.frame(
  receptor_1 = seq_1ITB_split,
  receptor_2 = seq_3O4O_split,
  stringsAsFactors = FALSE
)

write.csv(contacts_df, "~/Dropbox/getcontacts/receptors_il1b/contact_alignment.csv")
